import { db } from '@/db';
import { properties } from '@/db/schema';

async function main() {
    const sampleProperties = [
        {
            title: 'Nashville Downtown Luxury Loft',
            description: 'Experience urban sophistication in this stunning 2,100 square foot loft in the heart of downtown Nashville. Floor-to-ceiling windows flood the space with natural light while offering breathtaking views of the city skyline. This industrial-chic residence features exposed brick walls, polished concrete floors, and soaring 14-foot ceilings that create an incredible sense of space. The open-concept design seamlessly blends the gourmet kitchen with high-end stainless steel appliances, custom cabinetry, and a large island perfect for entertaining. The primary suite boasts a spa-like bathroom with a rainfall shower and designer fixtures. Located within walking distance of Broadway\'s entertainment district, fine dining, and the vibrant arts scene, this loft offers the ultimate Nashville lifestyle. Building amenities include a rooftop terrace, fitness center, and secure parking. Whether you\'re a young professional or empty nester seeking city living, this property delivers modern luxury in Music City\'s most exciting neighborhood.',
            price: 875000,
            location: 'Nashville, TN',
            type: 'apartment',
            bedrooms: 2,
            bathrooms: 2,
            area: 2100,
            images: [
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688',
                'https://images.unsplash.com/photo-1493809842364-78817add7ffb',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2'
            ],
            featured: true,
            status: 'available',
            amenities: [
                'Floor-to-ceiling windows',
                'Exposed brick walls',
                'Rooftop terrace',
                'Fitness center',
                'Secure parking',
                'Smart home technology',
                'Stainless steel appliances',
                'Walk-in closets',
                'In-unit laundry',
                'Concierge service'
            ],
            yearBuilt: 2021,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            title: 'Phoenix Desert Modern Estate',
            description: 'Embrace desert living at its finest in this architectural masterpiece nestled in the foothills of Phoenix. This 5,200 square foot contemporary home showcases floor-to-ceiling glass walls that frame breathtaking panoramic views of the Sonoran Desert and distant mountain ranges. The open floor plan features soaring ceilings, clean lines, and a seamless indoor-outdoor flow. The gourmet kitchen is a chef\'s dream with top-of-the-line appliances, custom cabinetry, and a massive center island. The great room opens to an expansive covered patio perfect for Arizona\'s year-round outdoor living. The luxurious primary suite includes a private balcony, spa-like bathroom with a soaking tub, and an enormous walk-in closet. Three additional bedrooms provide ample space for family and guests. The resort-style backyard features a sparkling infinity pool, outdoor kitchen, fire pit, and lush desert landscaping. Smart home technology controls lighting, climate, and security throughout. Located in a prestigious gated community with hiking trails at your doorstep, this home offers the perfect blend of luxury and natural beauty.',
            price: 2450000,
            location: 'Phoenix, AZ',
            type: 'house',
            bedrooms: 4,
            bathrooms: 5,
            area: 5200,
            images: [
                'https://images.unsplash.com/photo-1613490493576-7fde63acd811',
                'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d',
                'https://images.unsplash.com/photo-1512917774080-9991f1c4c750'
            ],
            featured: false,
            status: 'available',
            amenities: [
                'Mountain views',
                'Infinity pool',
                'Outdoor kitchen',
                'Smart home system',
                'Gated community',
                'Three-car garage',
                'Solar panels',
                'Fire pit',
                'Desert landscaping',
                'Home theater',
                'Wine cellar',
                'Hiking trails access'
            ],
            yearBuilt: 2022,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            title: 'Philadelphia Historic Row House',
            description: 'Step into history with this beautifully restored 19th-century row house in Philadelphia\'s charming Fairmount neighborhood. This 2,800 square foot gem perfectly balances historic character with modern amenities. Original hardwood floors, exposed brick walls, and ornate moldings have been meticulously preserved, while the home has been updated with contemporary comforts throughout. The main level features a formal living room with a decorative fireplace, dining room ideal for entertaining, and a completely renovated kitchen with marble countertops and professional-grade appliances. Three spacious bedrooms on the upper floors include a primary suite with an en-suite bathroom featuring subway tile and vintage-inspired fixtures. The finished basement provides additional living space perfect for a home office or media room. A private rear courtyard offers a peaceful outdoor retreat in the heart of the city. Located just blocks from the Philadelphia Museum of Art, Schuylkill River Trail, and vibrant restaurant scene, this home offers the perfect blend of historic charm and urban convenience.',
            price: 695000,
            location: 'Philadelphia, PA',
            type: 'house',
            bedrooms: 3,
            bathrooms: 3,
            area: 2800,
            images: [
                'https://images.unsplash.com/photo-1580587771525-78b9dba3b914',
                'https://images.unsplash.com/photo-1564013799919-ab600027ffc6',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c',
                'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea',
                'https://images.unsplash.com/photo-1600585154526-990dced4db0d'
            ],
            featured: false,
            status: 'pending',
            amenities: [
                'Original hardwood floors',
                'Exposed brick',
                'Decorative fireplace',
                'Marble countertops',
                'Private courtyard',
                'Finished basement',
                'Central air',
                'Updated electrical',
                'Walking distance to museums',
                'Street parking'
            ],
            yearBuilt: 2020,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            title: 'San Diego Beachfront Luxury Condo',
            description: 'Wake up to the sound of waves in this spectacular beachfront condominium in San Diego\'s coveted Pacific Beach neighborhood. This 1,800 square foot residence on the top floor offers unobstructed ocean views from nearly every room through expansive windows and a private balcony that extends the living space outdoors. The open-concept living area features contemporary finishes, hardwood floors, and a seamless flow from the modern kitchen to the dining and living areas. The gourmet kitchen boasts quartz countertops, stainless steel appliances, and custom cabinetry. Two spacious bedrooms include a primary suite with direct ocean views, a spa-inspired bathroom with dual vanities, and a generous walk-in closet. The second bedroom is perfect for guests or a home office. Building amenities include a heated pool, fitness center, sauna, and direct beach access. Located steps from the boardwalk, world-class dining, and vibrant nightlife, this condo offers the ultimate Southern California coastal lifestyle. Additional features include two assigned parking spaces and secure storage.',
            price: 1350000,
            location: 'San Diego, CA',
            type: 'condo',
            bedrooms: 2,
            bathrooms: 2,
            area: 1800,
            images: [
                'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4',
                'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9'
            ],
            featured: true,
            status: 'available',
            amenities: [
                'Ocean views',
                'Private balcony',
                'Direct beach access',
                'Heated pool',
                'Fitness center',
                'Sauna',
                'Two parking spaces',
                'Secure storage',
                'Concierge',
                'Hardwood floors',
                'Quartz countertops',
                'Central AC'
            ],
            yearBuilt: 2023,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            title: 'Charlotte Uptown High-Rise Apartment',
            description: 'Experience sophisticated city living in this stunning one-bedroom apartment located on the 25th floor of Charlotte\'s premier luxury high-rise. This 1,200 square foot residence offers floor-to-ceiling windows that showcase spectacular panoramic views of the Charlotte skyline. The open-concept layout features gleaming hardwood floors, modern lighting fixtures, and designer finishes throughout. The gourmet kitchen includes stainless steel appliances, granite countertops, and a breakfast bar perfect for casual dining. The spacious living area flows seamlessly to a private balcony where you can enjoy your morning coffee while taking in the city views. The bedroom suite provides a peaceful retreat with a walk-in closet and spa-like bathroom featuring a soaking tub and separate glass shower. Residents enjoy access to an incredible array of amenities including a rooftop pool, state-of-the-art fitness center, yoga studio, business center, and 24-hour concierge service. Located in the heart of uptown Charlotte, you\'re steps away from the city\'s best restaurants, entertainment venues, and cultural attractions. Valet parking and pet-friendly policies make this the perfect urban oasis.',
            price: 485000,
            location: 'Charlotte, NC',
            type: 'apartment',
            bedrooms: 1,
            bathrooms: 1,
            area: 1200,
            images: [
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1493809842364-78817add7ffb'
            ],
            featured: false,
            status: 'available',
            amenities: [
                'City skyline views',
                'Rooftop pool',
                'Fitness center',
                'Yoga studio',
                '24-hour concierge',
                'Valet parking',
                'Pet-friendly',
                'Business center',
                'Private balcony',
                'Hardwood floors',
                'Stainless steel appliances',
                'Walk-in closet'
            ],
            yearBuilt: 2022,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            title: 'Minneapolis Lakefront Modern House',
            description: 'Discover lakeside luxury in this spectacular modern home situated on the shores of Lake Calhoun in Minneapolis. This 4,500 square foot architectural gem features walls of glass that frame stunning water views and bring the outdoors in. The open-concept main level showcases a chef\'s kitchen with custom cabinetry, top-of-the-line appliances, and a large island that serves as the heart of the home. The great room with a linear fireplace opens to a covered deck perfect for enjoying Minnesota\'s beautiful seasons. Four spacious bedrooms include a primary suite with lake views, a luxurious bathroom with heated floors, and dual walk-in closets. The finished lower level provides additional living space with a recreation room, wet bar, and guest suite. Outside, the property features a private dock, landscaped yard, and patio with an outdoor fireplace. Smart home technology controls everything from lighting to security. Located in one of Minneapolis\' most desirable neighborhoods, you\'re minutes from the city\'s chain of lakes, bike trails, and vibrant dining scene. This is lakeside living at its finest.',
            price: 1875000,
            location: 'Minneapolis, MN',
            type: 'house',
            bedrooms: 4,
            bathrooms: 4,
            area: 4500,
            images: [
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d',
                'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4',
                'https://images.unsplash.com/photo-1613490493576-7fde63acd811',
                'https://images.unsplash.com/photo-1512917774080-9991f1c4c750'
            ],
            featured: false,
            status: 'available',
            amenities: [
                'Lake views',
                'Private dock',
                'Smart home system',
                'Linear fireplace',
                'Covered deck',
                'Finished lower level',
                'Wet bar',
                'Outdoor fireplace',
                'Heated floors',
                'Three-car garage',
                'Landscaped yard',
                'Bike trail access'
            ],
            yearBuilt: 2021,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            title: 'Atlanta Buckhead Office Space',
            description: 'Elevate your business in this premier Class A office space located in the heart of Buckhead, Atlanta\'s most prestigious business district. This 12,000 square foot space on the 18th floor offers breathtaking views of the Atlanta skyline through floor-to-ceiling windows. The modern open layout features high ceilings, polished concrete floors, and abundant natural light throughout. The space includes a sophisticated reception area, multiple private offices, spacious conference rooms with state-of-the-art AV technology, and large collaborative work areas. A modern kitchen and break room provide amenities for your team. The building offers exceptional amenities including a business center, fitness facility, covered parking garage with reserved spaces, and 24/7 security. High-speed fiber internet connectivity ensures your business stays connected. Located at the intersection of Peachtree and Lenox Roads, you\'re in the center of Atlanta\'s premier shopping, dining, and entertainment district. MARTA access is steps away, and you\'re minutes from major highways. This turnkey office space is perfect for established businesses looking to make a statement or growing companies ready to scale.',
            price: 3200000,
            location: 'Atlanta, GA',
            type: 'commercial',
            bedrooms: 0,
            bathrooms: 4,
            area: 12000,
            images: [
                'https://images.unsplash.com/photo-1497366216548-37526070297c',
                'https://images.unsplash.com/photo-1497366811353-6870744d04b2',
                'https://images.unsplash.com/photo-1497215842964-222b430dc094',
                'https://images.unsplash.com/photo-1497366754035-f200968a6e72',
                'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab'
            ],
            featured: false,
            status: 'available',
            amenities: [
                'Skyline views',
                'Reception area',
                'Conference rooms',
                'AV technology',
                'Modern kitchen',
                'Covered parking',
                '24/7 security',
                'Fiber internet',
                'MARTA access',
                'Fitness facility',
                'Business center',
                'High ceilings'
            ],
            yearBuilt: 2020,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            title: 'Las Vegas Strip-View Luxury Condo',
            description: 'Experience the excitement of Las Vegas living in this spectacular two-bedroom condominium with unobstructed views of the world-famous Las Vegas Strip. Located on the 35th floor of an exclusive high-rise tower, this 1,650 square foot residence showcases floor-to-ceiling windows that frame the dazzling city lights. The modern open-concept design features high-end finishes including Italian marble flooring, custom lighting, and sleek contemporary fixtures. The gourmet kitchen boasts top-of-the-line appliances, granite countertops, and a large center island. The spacious living area flows to a private balcony where you can watch the Bellagio fountains and nightly Strip shows from the comfort of home. The primary suite includes a walk-in closet and spa-like bathroom with a soaking tub and separate shower. A second bedroom provides flexibility for guests or a home office. Residents enjoy resort-style amenities including a rooftop infinity pool, full-service spa, fitness center, valet parking, and concierge services. Located just minutes from world-class dining, entertainment, and shopping, this condo offers the ultimate Las Vegas lifestyle with the convenience of being away from the crowds.',
            price: 825000,
            location: 'Las Vegas, NV',
            type: 'condo',
            bedrooms: 2,
            bathrooms: 2,
            area: 1650,
            images: [
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d',
                'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
                'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4'
            ],
            featured: false,
            status: 'sold',
            amenities: [
                'Strip views',
                'Rooftop infinity pool',
                'Full-service spa',
                'Fitness center',
                'Valet parking',
                'Concierge service',
                'Private balcony',
                'Italian marble floors',
                'Smart home features',
                'Walk-in closets',
                'Soaking tub',
                'Secured entry'
            ],
            yearBuilt: 2023,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Scottsdale Golf Course Estate',
            description: 'Live the resort lifestyle in this magnificent estate overlooking the pristine fairways of one of Scottsdale\'s most prestigious golf courses. This 6,800 square foot masterpiece sits on over an acre of lush desert landscaping with unobstructed mountain and golf course views. The grand entry leads to soaring ceilings and expansive living spaces filled with natural light. The gourmet kitchen features professional-grade appliances, custom cabinetry, butler\'s pantry, and a large island perfect for entertaining. The luxurious primary suite is a private sanctuary with a sitting area, spa-like bathroom with dual vanities and soaking tub, and enormous walk-in closet. Five additional bedrooms provide ample space for family and guests. The resort-style backyard is an entertainer\'s dream featuring a sparkling pool with waterfall, built-in BBQ and bar, multiple seating areas, and a fire pit surrounded by putting green. Additional features include a home theater, wine cellar, four-car garage, and smart home technology throughout. The exclusive guard-gated community offers world-class amenities including tennis courts, clubhouse, and fitness center. This is Arizona luxury living at its finest.',
            price: 4250000,
            location: 'Scottsdale, AZ',
            type: 'house',
            bedrooms: 6,
            bathrooms: 7,
            area: 6800,
            images: [
                'https://images.unsplash.com/photo-1613490493576-7fde63acd811',
                'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4',
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d',
                'https://images.unsplash.com/photo-1512917774080-9991f1c4c750'
            ],
            featured: true,
            status: 'available',
            amenities: [
                'Golf course views',
                'Mountain views',
                'Pool with waterfall',
                'Outdoor kitchen',
                'Putting green',
                'Fire pit',
                'Home theater',
                'Wine cellar',
                'Four-car garage',
                'Smart home system',
                'Guard-gated community',
                'Tennis courts'
            ],
            yearBuilt: 2022,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            title: 'Santa Monica Beach House',
            description: 'Own a piece of paradise in this stunning beach house just steps from the Santa Monica shoreline. This 3,400 square foot contemporary residence perfectly captures the essence of California coastal living. Designed for indoor-outdoor living, the home features walls of glass that open to create a seamless flow between interior spaces and the beautiful backyard oasis. The open-concept main level showcases a chef\'s kitchen with top-of-the-line appliances, custom cabinetry, and a large island that overlooks the living and dining areas. Wide-plank hardwood floors and coastal-inspired finishes create a relaxed yet sophisticated atmosphere. Four bedrooms include a primary suite with ocean breezes, a luxurious bathroom, and private balcony. The backyard is an entertainer\'s dream with a heated pool, spa, outdoor shower, built-in BBQ, and multiple lounging areas surrounded by mature landscaping for privacy. Additional features include a two-car garage, smart home technology, and central AC. Located in one of Santa Monica\'s most coveted neighborhoods, you\'re a short walk to the beach, Main Street\'s shopping and dining, and the Santa Monica Pier. This is the California dream realized.',
            price: 5000000,
            location: 'Santa Monica, CA',
            type: 'house',
            bedrooms: 4,
            bathrooms: 4,
            area: 3400,
            images: [
                'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
                'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
                'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d',
                'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9',
                'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4'
            ],
            featured: false,
            status: 'pending',
            amenities: [
                'Walk to beach',
                'Heated pool',
                'Spa',
                'Outdoor shower',
                'Built-in BBQ',
                'Smart home system',
                'Central AC',
                'Two-car garage',
                'Hardwood floors',
                'Private balcony',
                'Mature landscaping',
                'Ocean breezes'
            ],
            yearBuilt: 2021,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'Brooklyn Heights Brownstone Apartment',
            description: 'Discover classic New York living in this beautifully renovated apartment within a historic Brooklyn Heights brownstone. This 1,450 square foot two-bedroom residence perfectly balances original architectural details with modern conveniences. High ceilings, original hardwood floors, decorative moldings, and large windows create an elegant and inviting atmosphere filled with natural light. The renovated kitchen features marble countertops, stainless steel appliances, and custom cabinetry while maintaining the home\'s classic charm. The spacious living and dining areas provide perfect spaces for entertaining. Two generous bedrooms include a primary suite with an en-suite bathroom featuring vintage-inspired fixtures and subway tile. Original pocket doors, exposed brick accents, and a decorative fireplace add character throughout. The building includes a common garden, laundry facilities, and storage. Located on one of Brooklyn Heights\' most beautiful tree-lined streets, you\'re moments from the Promenade with stunning Manhattan skyline views, Brooklyn Bridge Park, and a vibrant neighborhood filled with cafes, restaurants, and boutiques. Multiple subway lines provide easy access to Manhattan. This is Brooklyn brownstone living at its finest.',
            price: 1125000,
            location: 'Brooklyn, NY',
            type: 'apartment',
            bedrooms: 2,
            bathrooms: 2,
            area: 1450,
            images: [
                'https://images.unsplash.com/photo-1580587771525-78b9dba3b914',
                'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
                'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c',
                'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea'
            ],
            featured: false,
            status: 'available',
            amenities: [
                'High ceilings',
                'Original hardwood',
                'Decorative moldings',
                'Marble countertops',
                'Exposed brick',
                'Decorative fireplace',
                'Common garden',
                'Laundry facilities',
                'Storage',
                'Tree-lined street',
                'Near subway',
                'Historic building'
            ],
            yearBuilt: 2020,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            title: 'Honolulu Beachfront Development Land',
            description: 'Rare opportunity to own a spectacular 2.5-acre oceanfront parcel in one of Honolulu\'s most sought-after coastal areas. This prime development land offers 200 feet of pristine beachfront with white sand and crystal-clear waters. The gently sloping property provides breathtaking panoramic views of the Pacific Ocean, neighboring islands, and stunning sunsets. Zoned for residential development, this land presents an incredible opportunity to build your dream estate or develop luxury oceanfront homes. The property features mature tropical landscaping, coconut palms, and natural rock formations. Utilities including water, electricity, and fiber internet are available at the property line. Located in an exclusive area known for its natural beauty and privacy, yet convenient to Honolulu\'s world-class amenities, fine dining, shopping, and cultural attractions. The property is minutes from championship golf courses, hiking trails, and water sports. Environmental studies have been completed and are available for review. This is an exceptionally rare opportunity to own prime oceanfront land in Hawaii, perfect for visionary developers or those seeking to create their own private paradise. Pre-development planning assistance available.',
            price: 8500000,
            location: 'Honolulu, HI',
            type: 'land',
            bedrooms: 0,
            bathrooms: 0,
            area: 108900,
            images: [
                'https://images.unsplash.com/photo-1559827260-dc66d52bef19',
                'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
                'https://images.unsplash.com/photo-1520454974749-611b7248ffdb',
                'https://images.unsplash.com/photo-1583854049131-9ca55d5ef9bf',
                'https://images.unsplash.com/photo-1551244072-5d12893278ab'
            ],
            featured: false,
            status: 'available',
            amenities: [
                'Ocean views',
                '200 feet beachfront',
                'White sand beach',
                'Zoned residential',
                'Utilities available',
                'Mature landscaping',
                'Environmental studies completed',
                'Coconut palms',
                'Natural rock formations',
                'Privacy',
                'Near golf courses',
                'Development potential'
            ],
            yearBuilt: 2024,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        }
    ];

    await db.insert(properties).values(sampleProperties);
    
    console.log('✅ Properties seeder completed successfully - 12 new properties added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});